package com.construct.jsjjgpt.webservice.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-12-29T13:25:37.635+08:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://service.webservice.jsjjgpt.construct.com/", name = "Projdata")
@XmlSeeAlso({ObjectFactory.class})
public interface Projdata {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "processData", targetNamespace = "http://service.webservice.jsjjgpt.construct.com/", className = "com.construct.jsjjgpt.webservice.service.ProcessData")
    @WebMethod
    @ResponseWrapper(localName = "processDataResponse", targetNamespace = "http://service.webservice.jsjjgpt.construct.com/", className = "com.construct.jsjjgpt.webservice.service.ProcessDataResponse")
    public java.lang.String processData(
        @WebParam(name = "reqPacket", targetNamespace = "")
        java.lang.String reqPacket
    );
}
