package com.construct.jsjjgpt.webservice.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-12-29T13:25:37.681+08:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "ProjdataService", 
                  wsdlLocation = "http://172.16.4.173:8080/JSJJGPTService/service/Projdata?wsdl",
                  targetNamespace = "http://service.webservice.jsjjgpt.construct.com/") 
public class ProjdataService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.webservice.jsjjgpt.construct.com/", "ProjdataService");
    public final static QName ProjdataPort = new QName("http://service.webservice.jsjjgpt.construct.com/", "ProjdataPort");
    static {
        URL url = null;
        try {
            url = new URL("http://172.16.4.173:8080/JSJJGPTService/service/Projdata?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProjdataService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.16.4.173:8080/JSJJGPTService/service/Projdata?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProjdataService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProjdataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProjdataService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProjdataService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProjdataService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProjdataService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns Projdata
     */
    @WebEndpoint(name = "ProjdataPort")
    public Projdata getProjdataPort() {
        return super.getPort(ProjdataPort, Projdata.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Projdata
     */
    @WebEndpoint(name = "ProjdataPort")
    public Projdata getProjdataPort(WebServiceFeature... features) {
        return super.getPort(ProjdataPort, Projdata.class, features);
    }

}
